name: Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Deploy to Jenkins"
        run: |
          curl http://${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_PASSWORD }}@${{ secrets.JENKINS_URL }}/job/gotoko_web/build?token=${{ secrets.JENKINS_TOKEN }}
